# Travis configurations are partially derived from trust.
# See ci/README.md for license information.

dist: xenial
language: rust
services: docker
sudo: required

addons:
  apt:
    update: true
    sources:
    - deadsnakes
    - ubuntu-toolchain-r-test

matrix:
  include:
    # Environment variables:
    # ----------------------
    #   `NO_FEATURES` - Do not test all permutations of features.
    #         Only enable all features on stable and specific-version checks.
    #   `ENABLE_FFI_TESTS` - Enable tests of the C FFI.
    #   `DISABLE_TESTS` - Disable all dev builds, including tests and benchmarks.
    #   `DISABLE_BENCHES` - Do not compile benchmarks. Benchmarks are never run.
    #   `NO_STD` - Do not use the std library.
    #   `DISABLE_PROPERTY_TESTS` - Disable property-based tests: quickcheck and proptest.
    - rust: stable
      env: TARGET=x86_64-unknown-linux-gnu ENABLE_FFI_TESTS=1 ENABLE_DERIVE_TESTS=1

    # For compile-time reasons, disable benches on all besides rust/stable.
    - rust: beta
      env: TARGET=x86_64-unknown-linux-gnu DISABLE_BENCHES=1 NO_FEATURES=1

    - rust: stable
      env: TARGET=x86_64-unknown-linux-gnu NO_STD=1 ENABLE_LIBM=1 DISABLE_BENCHES=1 NO_FEATURES=1

    - rust: nightly
      env: TARGET=x86_64-unknown-linux-gnu NO_STD=1 DISABLE_BENCHES=1 NO_FEATURES=1

    # Proptest does not work until versions >= 1.43.0, disable it.
    - rust: 1.37.0
      env: TARGET=x86_64-unknown-linux-gnu DISABLE_PROPERTY_TESTS=1 DISABLE_BENCHES=1

    # Currently a bug in Criterion for Rustc versions 1.38.0 and 1.39.0,
    # where walkdir uses #[cfg(doctest)].
    - rust: 1.41.0
      env: TARGET=x86_64-unknown-linux-gnu DISABLE_PROPERTY_TESTS=1 DISABLE_BENCHES=1

    # Should fully support tests
    - rust: 1.45.0
      env: TARGET=x86_64-unknown-linux-gnu DISABLE_BENCHES=1

    # Android
    - env: TARGET=aarch64-linux-android DISABLE_TESTS=1 NO_FEATURES=1
    - env: TARGET=arm-linux-androideabi DISABLE_TESTS=1 NO_FEATURES=1
    - env: TARGET=armv7-linux-androideabi DISABLE_TESTS=1 NO_FEATURES=1
    - env: TARGET=i686-linux-android DISABLE_TESTS=1 NO_FEATURES=1
    - env: TARGET=x86_64-linux-android DISABLE_TESTS=1 NO_FEATURES=1

    # iOS
    - env: TARGET=aarch64-apple-ios DISABLE_TESTS=1 NO_FEATURES=1
      os: osx
    - env: TARGET=armv7-apple-ios DISABLE_TESTS=1 NO_FEATURES=1
      os: osx
    - env: TARGET=armv7s-apple-ios DISABLE_TESTS=1 NO_FEATURES=1
      os: osx
    - env: TARGET=i386-apple-ios DISABLE_TESTS=1 NO_FEATURES=1
      os: osx
    - env: TARGET=x86_64-apple-ios DISABLE_TESTS=1 NO_FEATURES=1
      os: osx

    # Linux
    # All of the following fail to compile benches due to an issue
    # with the binary format (ELF) and relocations in the bench binary.
    # Every test, except for i686-unknown-linux-musl, fails on the benches.
    - env: TARGET=aarch64-unknown-linux-gnu DISABLE_BENCHES=1 NO_FEATURES=1
    - env: TARGET=arm-unknown-linux-gnueabi DISABLE_BENCHES=1 NO_FEATURES=1
    - env: TARGET=armv7-unknown-linux-gnueabihf DISABLE_BENCHES=1 NO_FEATURES=1
    - env: TARGET=i686-unknown-linux-gnu DISABLE_BENCHES=1 NO_FEATURES=1
    - env: TARGET=i686-unknown-linux-musl NO_FEATURES=1
    - env: TARGET=mips-unknown-linux-gnu DISABLE_BENCHES=1 NO_FEATURES=1
    - env: TARGET=mips64-unknown-linux-gnuabi64 DISABLE_BENCHES=1 NO_FEATURES=1
    - env: TARGET=mips64el-unknown-linux-gnuabi64 DISABLE_BENCHES=1 NO_FEATURES=1
    - env: TARGET=mipsel-unknown-linux-gnu DISABLE_BENCHES=1 NO_FEATURES=1
    - env: TARGET=powerpc-unknown-linux-gnu DISABLE_BENCHES=1 NO_FEATURES=1
    - env: TARGET=powerpc64-unknown-linux-gnu DISABLE_TESTS=1 NO_FEATURES=1
    - env: TARGET=powerpc64le-unknown-linux-gnu DISABLE_BENCHES=1 NO_FEATURES=1
    - env: TARGET=s390x-unknown-linux-gnu DISABLE_TESTS=1 NO_FEATURES=1
    - env: TARGET=x86_64-unknown-linux-gnu DISABLE_BENCHES=1 NO_FEATURES=1
    - env: TARGET=x86_64-unknown-linux-musl DISABLE_BENCHES=1 NO_FEATURES=1

    # OSX
    # Use compiler 1.41.0, which cannot compile a modern proptest or quickcheck.
    - env: TARGET=i686-apple-darwin DISABLE_PROPERTY_TESTS=1 NO_FEATURES=1
      os: osx
    - env: TARGET=x86_64-apple-darwin NO_FEATURES=1
      os: osx

    # *BSD
    - env: TARGET=i686-unknown-freebsd DISABLE_TESTS=1 NO_FEATURES=1
    - env: TARGET=x86_64-unknown-freebsd DISABLE_TESTS=1 NO_FEATURES=1
    - env: TARGET=x86_64-unknown-netbsd DISABLE_TESTS=1 NO_FEATURES=1

    # Windows
    # Benches fail since the following option is not recognized:
    #   '--enable-long-section-names'
    - env: TARGET=x86_64-pc-windows-gnu DISABLE_BENCHES=1 NO_FEATURES=1

    - rust: nightly
      os: windows
      install:
      script: DISABLE_CROSS=1 bash ci/script.sh

  allow_failures:
    - rust: nightly

before_install:
  - set -e
  - rustup self update

install:
  # Build essential is already installed, so we just need GCC-7, Python3.6+ and Googletest.
  - if [ ! -z $ENABLE_FFI_TESTS ]; then
      sudo apt-get install gcc-7 g++-7 -y;
      sudo apt-get install python3.6 -y;
      sh ci/install_gtest.sh;
    fi
  # Install rust target and source the correct environment.
  - sh ci/install_rust.sh
  - source ~/.cargo/env || true

script:
  - if [ ! -z $ENABLE_FFI_TESTS ]; then
      export CC=gcc-7;
      export CXX=g++-7;
    fi
  - bash ci/script.sh

after_script: set +e
